conv2d:
#  group1:
#    batch: [8, 16]
#    in_channels: [256, 512]
#    out_channels: [512, 1024]
#    input_height: [112, 224]
#    input_width: [112, 224]
#    kernel_size: [3, 7]
  group1:
    batch: [4, 8]
    in_channels: [128, 256]
    out_channels: [256, 512]
    input_height: [56, 112]
    input_width: [56, 112]
    kernel_size: [3, 5]
  group2:
    batch: [2, 4]
    in_channels: [64, 128]
    out_channels: [64, 256]
    input_height: [28, 56]
    input_width: [28, 56]
    kernel_size: [1, 3]
  group3:
    batch: [1, 2]
    in_channels: [8, 64]
    out_channels: [8, 64]
    input_height: [8, 28]
    input_width: [8, 28]
    kernel_size: [1, 3]

dense:
  group1:
    batch: [512, 2048]
    in_features: [2048, 4096]
    out_features: [2048, 4096]
  group2:
    batch: [128, 512]
    in_features: [512, 2048]
    out_features: [512, 2048]
  group3:
    batch: [1, 128]
    in_features: [64, 512]
    out_features: [64, 512]

matmul:
  group1:
    M: [1024, 2048]
    K: [1024, 2048]
    N: [1024, 2048]
  group2:
    M: [256, 1024]
    K: [128, 1024]
    N: [256, 1024]
  group3:
    M: [32, 256]
    K: [32, 256]
    N: [32, 256]

batch_norm:
  group1:
    batch: [8, 16]
    channels: [256, 512]
    input_height: [112, 224]
    input_width: [112, 224]
  group2:
    batch: [4, 8]
    channels: [128, 256]
    input_height: [56, 112]
    input_width: [56, 112]
  group3:
    batch: [4, 8]
    channels: [96, 128]
    input_height: [56, 112]
    input_width: [56, 112]
  group4:
    batch: [2, 4]
    channels: [64, 96]
    input_height: [32, 64]
    input_width: [32, 64]
  group5:
    batch: [1, 4]
    channels: [32, 64]
    input_height: [24, 48]
    input_width: [24, 48]
  group6:
    batch: [1, 2]
    channels: [16, 32]
    input_height: [16, 32]
    input_width: [16, 32]
  group7:
    batch: [1, 2]
    channels: [8, 16]
    input_height: [8, 24]
    input_width: [8, 24]
  group8:
    batch: [1, 1]
    channels: [1, 8]
    input_height: [8, 24]
    input_width: [8, 24]

relu:
  group1:
    batch: [8, 16]
    channels: [256, 512]
    input_height: [112, 224]
    input_width: [112, 224]
  group2:
    batch: [1, 8]
    channels: [8, 256]
    input_height: [16, 112]
    input_width: [16, 112]

bias_add:
  group1:
    batch: [8, 16]
    channels: [256, 512]
    input_height: [112, 224]
    input_width: [112, 224]
  group2:
    batch: [2, 8]
    channels: [64, 256]
    input_height: [32, 112]
    input_width: [32, 112]
  group3:
    batch: [1, 2]
    channels: [8, 64]
    input_height: [8, 32]
    input_width: [8, 32]

softmax:
  group1:
    batch: [512, 2048]
    features: [4096, 8192]
  group2:
    batch: [128, 512]
    features: [512, 4096]
  group3:
    batch: [1, 128]
    features: [64, 512]

avg_pool2d:
  group1:
    batch: [8, 16]
    pool_channels: [256, 512]
    input_height: [112, 224]
    input_width: [112, 224]
    pool_size: [5, 7]
    stride: [1, 2]
  group2:
    batch: [2, 8]
    pool_channels: [64, 256]
    input_height: [32, 112]
    input_width: [32, 112]
    pool_size: [3, 5]
    stride: [2, 3]
  group3:
    batch: [1, 2]
    pool_channels: [8, 64]
    input_height: [8, 32]
    input_width: [8, 32]
    pool_size: [2, 3]
    stride: [2, 4]